### ISSUE TITLE
Fetch: throw specific TimeoutError

### ISSUE THREAD

**Issue by mrtnzlml** [mrtnzlml/quick-payments#32]
So it's possible to check easily when the fetch failed because of an error.

Here: https://github.com/mrtnzlml/quick-payments/blob/b1fcb567a4c679da023aae39f978ea44784bc548/frontend/npm/fetch/src/fetchWithRetries.js#L52-L57

TODO:

- [x] test NPM version in the real application
- [x] add info about `TimeoutError` to the documentation
- [x] remove unstable flag

**Comment by tbergq** [comment]
So when will this be implemented and released, I would love to start using this package 😊

**Comment by mrtnzlml** [comment]
not done yet - exposed only as a `unstable_TimeoutError`

**Comment by mrtnzlml** [comment]
Done - `TimeoutError` and `ResponseError` are now exposed publicly without the unstable tag. 🥂
