### ISSUE TITLE
Fetch: Cannot find module 'babel-runtime/core-js/promise'

### ISSUE THREAD

**Issue by zbycz** [mrtnzlml/quick-payments#43]
Compiled code of the `fetchWithRetries` requires(`babel-runtime`), but this isnt disclosed in package.json dependencies. (Thus a run with "yarn --production" fails)

See here: https://unpkg.com/@mrtnzlml/fetch@1.3.0/src/fetchWithRetries.js

**Comment by mrtnzlml** [comment]
Yes, you are right - thanks for pointing it out.  It is fixed in version `^1.4`.

**Comment by zbycz** [comment]
Great, thanks also for the PR :-)  
#holidays-fe likes!
