### ISSUE TITLE
TimeoutError - Undefined is not a function

### ISSUE THREAD

**Issue by tbergq** [mrtnzlml/quick-payments#44]
I got this red-screen after timeout 3 times (on android). 

<img width="393" alt="screenshot 2019-01-14 at 12 15 10" src="https://user-images.githubusercontent.com/7705041/51128523-0f717c00-17f6-11e9-9171-71f2ee03d7fb.png">

**Comment by mrtnzlml** [comment]
Is it possible that in your JS environment function `Object.setPrototypeOf` simply doesn't exist? Can you please try it?

**Comment by tbergq** [comment]
Yes, it is undefined in Android JS environment, but works in ios. 

Should every consumer using android add a polyfill for this or will you add it to the package?

**Comment by mrtnzlml** [comment]
Let me think a little bit about it. The fast fix is to add the polyfill, yes. Not sure how to prevent this in the future. The JS version on Android is simply missing some core features.

**Comment by tbergq** [comment]
> The JS version on Android is simply missing some core features

Yes, I am aware of it. But. currently (at least) two of your consumers are RN apps (mobile and margarita)

**Comment by mrtnzlml** [comment]
Please try to use the latest version (1.5.1) and let me know if it's fixed or not.

**Comment by tbergq** [comment]
It no longer crashes, but `error instanceof TimeoutError` evaluates to false.
